### ISSUE TITLE
When the screen size is reduced, the cards move away from the screen borders

### ISSUE THREAD

**Issue by VladislavYakonyuk** [bixat/flexible_wrap#14]
I noticed a problem that when I resized the screen, my cards would move out of bounds (in my example, this was clearly visible due to the indentations from the screen borders)

I thought the problem was related to my widget layout, but no, the demo that the developers provided on pub.dev site also has this problem.

The first screen shows 3 horizontally and 6 vertically, and 2 more at the very end of the list. By simple math we understand that 3 * 6 + 2 = 20 items are displayed on the screen.

Already on the second screen, when the screen width became even smaller, 2 horizontal and 7 vertical are displayed, total 2 * 7 = 14. The remaining 6 went off the screen

On the last screenshot we see these very cards that appeared out of nowhere

Could you fix this problem? I really like this package as it is the only good solution I found on the internet

![telegram-cloud-photo-size-2-5352566911076001202-y](https://github.com/user-attachments/assets/d117cc78-161d-4bdd-94bb-b7dfdfab7317)

![telegram-cloud-photo-size-2-5352566911076001194-y](https://github.com/user-attachments/assets/d4305e81-6b40-4508-913f-e7f18902f479)

![image](https://github.com/user-attachments/assets/d6bff04c-978e-4fbc-ab63-189414dacb38)

**Comment by M97Chahboun** [comment]
Thank you for your report! It looks like the solution is to wrap the `FlexibleWrap` widget with a `SingleChildScrollView`. You can see an example of this implementation in the package's demo [here](https://github.com/bixat/flexible_wrap/blob/a370d9ee9b4112cb8183fa815b63a859b81206ee/example/lib/main.dart#L43).

If you have any further questions or need additional help, feel free to ask!

**Comment by VladislavYakonyuk** [comment]
> Thank you for your report! It looks like the solution is to wrap the `FlexibleWrap` widget with a `SingleChildScrollView`. You can see an example of this implementation in the package's demo [here](https://github.com/bixat/flexible_wrap/blob/a370d9ee9b4112cb8183fa815b63a859b81206ee/example/lib/main.dart#L43).
> 
> If you have any further questions or need additional help, feel free to ask!

Thanks for your reply!!! I ran a demo in which I caught the cards jumping 2 times. 

Demo from main branch

<img width="666" alt="image" src="https://github.com/user-attachments/assets/3509a00a-f8be-4dbe-a6ef-4d131c86bd3e">
<img width="666" alt="image" src="https://github.com/user-attachments/assets/94372cdf-1186-4ee1-b23e-a8b55d2ba237">
<img width="666" alt="image" src="https://github.com/user-attachments/assets/ae038a6d-3297-4055-9564-f2efdafde3f9">
<img width="666" alt="image" src="https://github.com/user-attachments/assets/a873ba3d-1c0c-4fab-8899-c97082fabe28">

**Comment by M97Chahboun** [comment]
Thank you for bringing this to my attention! I’ve noticed the issue with some items being hidden and will investigate further to find a solution.

**Comment by VladislavYakonyuk** [comment]
Thank you! Please let me know how it turns out

**Comment by M97Chahboun** [comment]
@VladislavYakonyuk Done ✅

**Comment by VladislavYakonyuk** [comment]
> @VladislavYakonyuk Done ✅

Thank you so much!

It works for me, already put the updates in my project

**Comment by M97Chahboun** [comment]
That's good, i deployed v1.0.1 to pub.dev 👍🏾
